import { Theme } from './theme'

export const Colors = {
  background: Theme.colors.background,
  backgroundDeep: Theme.colors.backgroundDeep,
  surface: Theme.colors.surface,
  surfaceElevated: Theme.colors.surfaceElevated,
  surfaceMuted: Theme.colors.surfaceMuted,
  border: Theme.colors.border,
  text: Theme.colors.text,
  textMuted: Theme.colors.textMuted,
  lime: Theme.colors.lime,
  limePressed: Theme.colors.limePressed,
  dangerSurface: Theme.colors.dangerSurface,

  navy: Theme.colors.background,
  navyLight: Theme.colors.surfaceElevated,
  navyXLight: Theme.colors.surfaceMuted,
  amber: Theme.colors.lime,
  amberLight: '#263315',
  blueLight: Theme.colors.surfaceElevated,
  blueM: Theme.colors.textMuted,
  dark: Theme.colors.text,
  gray: Theme.colors.textMuted,
  grayLight: Theme.colors.background,
  grayMid: Theme.colors.border,
  white: Theme.colors.white,
  green: Theme.colors.success,
  greenLight: '#17351F',
  red: Theme.colors.danger,
  redLight: Theme.colors.dangerSurface,
  purple: Theme.colors.limeSoft,
}
